language: r
cache: packages
r:
  - bioc-release
  - bioc-devel
before_install:
  - cd dREG
r_github_packages:
  - jimhester/covr
  - jimhester/lintr
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
